name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.233.154.101 >> ~/.ssh/known_hosts

      - name: SSH and Deploy
        run: |
          ssh root@13.233.154.101 << 'EOF'
            cd /root/moviu/MoviuPython
            git pull origin main
            source venv/bin/activate
            pm2 restart moviu-app
          EOF
